---
- block:
  - name: download rustup
    get_url:
      url: "https://sh.rustup.rs"
      dest: "/tmp/rustup.sh"
      validate_certs: False
      mode: 0700

  - name: install rustup and rust nightly
    command: "sh /tmp/rustup.sh --default-toolchain nightly -y"

  - name: install rust language server (rls)
    command: /home/vagrant/.cargo/bin/rustup component add rls-preview

  - name: install rust sources for racer
    command: /home/vagrant/.cargo/bin/rustup component add rust-src

  - name: install rust analysis
    command: /home/vagrant/.cargo/bin/rustup component add rust-analysis

  - name: install racer (take ~20 minutes)
    command: /home/vagrant/.cargo/bin/cargo install racer

  become: yes
  become_user: vagrant
