---
- hosts: localhost
  become: true

  vars:
    username: "vagrant"
    home: "/home/{{ username }}"
    document_root: "/{{ username }}"

  pre_tasks:
    - name: Install stuff from Aptitude
      apt: 
        name="{{ item }}"
        state=present
        update_cache=yes 
        cache_valid_time=86400
      with_items:
       - git
       - tig
       - vim
       - gcc
       - gdb
       - bash-completion # Not included in the docker image
       - make
       - tree
       - htop
       - man-db
       - software-properties-common
       - python-dev
       - python-pip
       - python3-dev
       - python3-pip

  roles:
    - rust
    - zsh
    - neovim
