---
- hosts: localhost
  become: true

  vars:
    username: "vagrant"
    home: "/home/{{ username }}"
    document_root: "/{{ username }}"

  pre_tasks:
    - name: Install from Apt
      apt:
        # bash-completion is not in phusion
        name: ['sudo', 'git', 'tig', 'vim', 'gcc', 'gdb', 'bash-completion', 'make', 'tree', 'htop', 'man-db', 'software-properties-common', 'python3-dev', 'python3-pip']
        state: present
        update_cache: yes
        cache_valid_time: 14400 # 4 hours

  roles:
    - rust
    - zsh
    - neovim
